name: Vlad Bibire - Web Development, Design
exclude: ["node_modules", "gulpfile.js", "package.json"]
markdown: kramdown
highlighter: rouge
navigation:
  - title: home
    url: /index.html
  # - title: blog
  #   url: /blog.html
  - title: about
    url: /about.html
  - title: contact
    url: /contact.html
